Repository OCA/community-data-files, pull requests merged in 2021-12, with the labels that each got.

#92 [FIX] l10n_eu_nace: Bad type in pre migration with boolean attribute
  l10n_eu_nace/migrations/12.0.2.0.0/post-migration.py
  l10n_eu_nace/migrations/12.0.2.0.0/pre-migration.py
Labels: bug, needs review, bot is merging ⏳

#117 [14.0] account_tax_unece: script for v13 to v14 migration
  account_tax_unece/14.0.1.0.0/pre-migration.py
Labels: bot is merging ⏳

#123 [MIG]base_bank_from_iban: Migration to 15.0
  base_bank_from_iban/README.rst
  base_bank_from_iban/__init__.py
  base_bank_from_iban/__manifest__.py
  base_bank_from_iban/i18n/base_bank_from_iban.pot
  base_bank_from_iban/i18n/nl.po
  base_bank_from_iban/models/__init__.py
  base_bank_from_iban/models/account_journal.py
  base_bank_from_iban/models/res_bank.py
  base_bank_from_iban/models/res_partner_bank.py
  base_bank_from_iban/readme/CONFIGURE.rst
  base_bank_from_iban/readme/CONTRIBUTORS.rst
  base_bank_from_iban/readme/DESCRIPTION.rst
  base_bank_from_iban/readme/USAGE.rst
  base_bank_from_iban/static/description/icon.png
  base_bank_from_iban/static/description/index.html
  base_bank_from_iban/tests/__init__.py
  base_bank_from_iban/tests/test_base_bank_from_iban.py
  base_bank_from_iban/views/res_bank_view.xml
  setup/base_bank_from_iban/odoo/addons/base_bank_from_iban
  setup/base_bank_from_iban/setup.py
Labels: approved, bot is merging ⏳
