Repository OCA/community-data-files, pull requests merged in 2022-12, with the labels that each got.

#146 [16.0][MIG] account_tax_unece: Migration to 16.0
  account_tax_unece/README.rst
  account_tax_unece/__init__.py
  account_tax_unece/__manifest__.py
  account_tax_unece/data/unece_tax_categ.xml
  account_tax_unece/data/unece_tax_type.xml
  account_tax_unece/i18n/account_tax_unece.pot
  account_tax_unece/i18n/de.po
  account_tax_unece/models/__init__.py
  account_tax_unece/models/account_tax.py
  account_tax_unece/models/account_tax_template.py
  account_tax_unece/models/res_company.py
  account_tax_unece/models/unece_code_list.py
  account_tax_unece/readme/CONFIGURE.rst
  account_tax_unece/readme/CONTRIBUTORS.rst
  account_tax_unece/readme/DESCRIPTION.rst
  account_tax_unece/static/description/icon.png
  account_tax_unece/static/description/index.html
  account_tax_unece/tests/__init__.py
  account_tax_unece/tests/test_tax_unece.py
  account_tax_unece/views/account_tax.xml
  account_tax_unece/views/account_tax_template.xml
  setup/account_tax_unece/odoo/addons/account_tax_unece
  setup/account_tax_unece/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#147 [MIG] [16.0] account_payment_unece
  account_payment_unece/README.rst
  account_payment_unece/__init__.py
  account_payment_unece/__manifest__.py
  account_payment_unece/data/account_payment_method.xml
  account_payment_unece/data/unece.xml
  account_payment_unece/i18n/account_payment_unece.pot
  account_payment_unece/i18n/de.po
  account_payment_unece/i18n/hr.po
  account_payment_unece/models/__init__.py
  account_payment_unece/models/account_payment_method.py
  account_payment_unece/models/unece_code_list.py
  account_payment_unece/readme/CONFIGURE.rst
  account_payment_unece/readme/CONTRIBUTORS.rst
  account_payment_unece/readme/DESCRIPTION.rst
  account_payment_unece/static/description/icon.png
  account_payment_unece/static/description/index.html
  account_payment_unece/views/account_payment_method.xml
  setup/account_payment_unece/odoo/addons/account_payment_unece
  setup/account_payment_unece/setup.py
Labels: approved, bot is merging ⏳

#141 [16.0][MIG] base_bank_from_iban: Migration to 16.0
  base_bank_from_iban/README.rst
  base_bank_from_iban/__init__.py
  base_bank_from_iban/__manifest__.py
  base_bank_from_iban/i18n/base_bank_from_iban.pot
  base_bank_from_iban/i18n/nl.po
  base_bank_from_iban/models/__init__.py
  base_bank_from_iban/models/res_bank.py
  base_bank_from_iban/models/res_partner_bank.py
  base_bank_from_iban/readme/CONFIGURE.rst
  base_bank_from_iban/readme/CONTRIBUTORS.rst
  base_bank_from_iban/readme/DESCRIPTION.rst
  base_bank_from_iban/readme/USAGE.rst
  base_bank_from_iban/static/description/icon.png
  base_bank_from_iban/static/description/index.html
  base_bank_from_iban/tests/__init__.py
  base_bank_from_iban/tests/test_base_bank_from_iban.py
  base_bank_from_iban/views/res_bank_view.xml
  base_bank_from_iban/wizards/__init__.py
  base_bank_from_iban/wizards/account_setup_bank_manual_config.py
  setup/base_bank_from_iban/odoo/addons/base_bank_from_iban
  setup/base_bank_from_iban/setup.py
Labels: bot is merging ⏳

#155 [15.0][FIX] account_tax_unece: remove HTML tags in 'note' of fiscal position
  account_tax_unece/models/res_company.py
Labels: bot is merging ⏳
