Repository OCA/community-data-files, pull requests merged in 2023-10, with the labels that each got.

#173 [15.0][IMP] community-data-files : test performance improvement
  base_bank_from_iban/tests/test_base_bank_from_iban.py
  base_iso3166/tests/test_iso3166.py
  product_fao_fishing/tests/test_product_fao_fishing.py
Labels: bot is merging ⏳

#174 [16.0][IMP] community-data-files: test performance improvement
  product_fao_fishing/tests/test_product_fao_fishing.py
Labels: bot is merging ⏳

#175 [14.0] dotfiles update needs manual intervention
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  l10n_eu_nace/data/make_data.py
  l10n_eu_nace/examples/NACE_REV2_bg.csv
  l10n_eu_nace/examples/NACE_REV2_cs.csv
  l10n_eu_nace/examples/NACE_REV2_da.csv
  l10n_eu_nace/examples/NACE_REV2_de.csv
  l10n_eu_nace/examples/NACE_REV2_el.csv
  l10n_eu_nace/examples/NACE_REV2_en.csv
  l10n_eu_nace/examples/NACE_REV2_es.csv
  l10n_eu_nace/examples/NACE_REV2_et.csv
  l10n_eu_nace/examples/NACE_REV2_fi.csv
  l10n_eu_nace/examples/NACE_REV2_fr.csv
  l10n_eu_nace/examples/NACE_REV2_hr.csv
  l10n_eu_nace/examples/NACE_REV2_hu.csv
  l10n_eu_nace/examples/NACE_REV2_it.csv
  l10n_eu_nace/examples/NACE_REV2_lt.csv
  l10n_eu_nace/examples/NACE_REV2_lv.csv
  l10n_eu_nace/examples/NACE_REV2_mt.csv
  l10n_eu_nace/examples/NACE_REV2_nl.csv
  l10n_eu_nace/examples/NACE_REV2_no.csv
  l10n_eu_nace/examples/NACE_REV2_pl.csv
  l10n_eu_nace/examples/NACE_REV2_pt.csv
  l10n_eu_nace/examples/NACE_REV2_ro.csv
  l10n_eu_nace/examples/NACE_REV2_ru.csv
  l10n_eu_nace/examples/NACE_REV2_sk.csv
  l10n_eu_nace/examples/NACE_REV2_sl.csv
  l10n_eu_nace/examples/NACE_REV2_sv.csv
  l10n_eu_nace/examples/NACE_REV2_tr.csv
  product_fao_fishing/i18n/product_fao_fishing.pot
  product_fao_fishing/views/product_fao_techinique_views.xml
Labels: help wanted, needs review, bot is merging ⏳

#172 [16.0] base_unece + account_tax_unece: AGPL -> LGPL
  account_tax_unece/__init__.py
  account_tax_unece/__manifest__.py
  account_tax_unece/models/__init__.py
  account_tax_unece/models/account_tax.py
  account_tax_unece/models/account_tax_template.py
  account_tax_unece/models/res_company.py
  account_tax_unece/models/unece_code_list.py
  account_tax_unece/tests/__init__.py
  account_tax_unece/tests/test_tax_unece.py
  account_tax_unece/views/account_tax.xml
  account_tax_unece/views/account_tax_template.xml
  base_unece/__init__.py
  base_unece/__manifest__.py
  base_unece/models/__init__.py
  base_unece/models/unece_code_list.py
  base_unece/views/unece_code_list.xml
Labels: bot is merging ⏳

#170 [IMP] base_bank_from_iban: automatically create banks with schwifty
  base_bank_from_iban/__manifest__.py
  base_bank_from_iban/models/res_partner_bank.py
  requirements.txt
Labels: approved, bot is merging ⏳
