Repository OCA/community-data-files, pull requests merged in 2024-05, with the labels that each got.

#198 [17.0] [FIX] base_bank_from_iban: dependencies
  base_bank_from_iban/__manifest__.py
  base_bank_from_iban/static/description/index.html
  requirements.txt
Labels: approved, bot is merging ⏳

#199 [16.0] [FIX] base_bank_from_iban: dependencies
  base_bank_from_iban/__manifest__.py
  base_bank_from_iban/static/description/index.html
  requirements.txt
Labels: approved, bot is merging ⏳

#187 [FIX] [15.0] base_iso3166 breaking tests if code is False
  base_iso3166/models/res_country.py
Labels: bot is merging ⏳, stale

#200 [MIG] l10n_eu_nace: Migration to 17.0
  l10n_eu_nace/README.rst
  l10n_eu_nace/__init__.py
  l10n_eu_nace/__manifest__.py
  l10n_eu_nace/i18n/ca.po
  l10n_eu_nace/i18n/es.po
  l10n_eu_nace/i18n/it.po
  l10n_eu_nace/i18n/l10n_eu_nace.pot
  l10n_eu_nace/pyproject.toml
  l10n_eu_nace/readme/CONTRIBUTORS.md
  l10n_eu_nace/readme/DESCRIPTION.md
  l10n_eu_nace/readme/USAGE.md
  l10n_eu_nace/security/ir.model.access.csv
  l10n_eu_nace/static/description/icon.png
  l10n_eu_nace/static/description/index.html
  l10n_eu_nace/tests/__init__.py
  l10n_eu_nace/tests/test_en_nace_request_results.py
  l10n_eu_nace/tests/test_res_partner_industry_eu_nace_wizard.py
  l10n_eu_nace/wizard/__init__.py
  l10n_eu_nace/wizard/res_partner_industry_eu_nace_wizard.py
  l10n_eu_nace/wizard/res_partner_industry_eu_nace_wizard_view.xml
Labels: bot is merging ⏳
