Repository OCA/community-data-files, pull requests merged in 2024-09, with the labels that each got.

#191 [15.0][IMP] base_bank_from_iban: automatically create banks with schwifty
  base_bank_from_iban/__manifest__.py
  base_bank_from_iban/models/res_partner_bank.py
  base_bank_from_iban/static/description/index.html
  requirements.txt
Labels: approved, bot is merging ⏳, stale

#205 [16.0] [UPD] l10n_eu_nace: migration script
  l10n_eu_nace/migrations/16.0.1.0.0/pre-migrate.py
Labels: approved, ready to merge, bot is merging ⏳

#206 [16.0][FIX] base_bank_from_iban: Handle correctly non IBAN accounts
  base_bank_from_iban/models/res_partner_bank.py
  base_bank_from_iban/tests/test_base_bank_from_iban.py
Labels: bot is merging ⏳
