Repository OCA/community-data-files, pull requests merged in 2025-02, with the labels that each got.

#211 [18.0][MIG] l10n_eu_product_adr_dangerous_goods: Migration to 18.0
  l10n_eu_product_adr_dangerous_goods/README.rst
  l10n_eu_product_adr_dangerous_goods/__init__.py
  l10n_eu_product_adr_dangerous_goods/__manifest__.py
  l10n_eu_product_adr_dangerous_goods/data/utility_models.xml
  l10n_eu_product_adr_dangerous_goods/i18n/es.po
  l10n_eu_product_adr_dangerous_goods/i18n/l10n_eu_product_adr_dangerous_goods.pot
  l10n_eu_product_adr_dangerous_goods/models/__init__.py
  l10n_eu_product_adr_dangerous_goods/models/product_product.py
  l10n_eu_product_adr_dangerous_goods/models/utility_models.py
  l10n_eu_product_adr_dangerous_goods/pyproject.toml
  l10n_eu_product_adr_dangerous_goods/readme/CONTRIBUTORS.md
  l10n_eu_product_adr_dangerous_goods/readme/CREDITS.md
  l10n_eu_product_adr_dangerous_goods/readme/DESCRIPTION.md
  l10n_eu_product_adr_dangerous_goods/readme/ROADMAP.md
  l10n_eu_product_adr_dangerous_goods/security/ir.model.access.csv
  l10n_eu_product_adr_dangerous_goods/static/description/icon.png
  l10n_eu_product_adr_dangerous_goods/static/description/index.html
  l10n_eu_product_adr_dangerous_goods/tests/__init__.py
  l10n_eu_product_adr_dangerous_goods/tests/test_product_product.py
  l10n_eu_product_adr_dangerous_goods/views/product_product.xml
Labels: approved, ready to merge, bot is merging ⏳

#222 [FIX][18.0] l10n_eu_product_adr: Fixed the kanban image in the adr label level.
  l10n_eu_product_adr/views/adr_label_views.xml
Labels: bot is merging ⏳

#228 [18.0][MIG] base_bank_from_iban: Migration to 18.0
  base_bank_from_iban/README.rst
  base_bank_from_iban/__init__.py
  base_bank_from_iban/__manifest__.py
  base_bank_from_iban/i18n/base_bank_from_iban.pot
  base_bank_from_iban/i18n/es.po
  base_bank_from_iban/i18n/hr.po
  base_bank_from_iban/i18n/it.po
  base_bank_from_iban/i18n/nl.po
  base_bank_from_iban/models/__init__.py
  base_bank_from_iban/models/res_bank.py
  base_bank_from_iban/models/res_partner_bank.py
  base_bank_from_iban/pyproject.toml
  base_bank_from_iban/readme/CONFIGURE.md
  base_bank_from_iban/readme/CONTRIBUTORS.md
  base_bank_from_iban/readme/DESCRIPTION.md
  base_bank_from_iban/readme/USAGE.md
  base_bank_from_iban/static/description/icon.png
  base_bank_from_iban/static/description/index.html
  base_bank_from_iban/tests/__init__.py
  base_bank_from_iban/tests/test_base_bank_from_iban.py
  base_bank_from_iban/views/res_bank_view.xml
  base_bank_from_iban/wizards/__init__.py
  base_bank_from_iban/wizards/account_setup_bank_manual_config.py
  requirements.txt
Labels: approved, bot is merging ⏳
